kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ubi8-nc
  namespace: quick-network-policy-images
  labels:
    app: ubi8-nc
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "ubi8-nc:latest"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: "https://github.com/MoOyeg/openshift-quick-networkpolicy-demo.git"
    contextDir: /image-build
  triggers:
    - type: ConfigChange
  runPolicy: Serial
